#!/usr/bin/env bash
#Creates a script that displays numbers and text from 1 to 20
n=1
while [ $n -le 20 ]
do
    echo "$n"
    case $n in
         4)
            echo "bad luck from china"
            ;;
        9)
            echo "bad luck from japan"
            ;;
        17)
            echo "bad luck from italy"
            ;;
   esac
   ((n++))
done
