#!/usr/bin/env bash
#checks the file and gives information about the file
fie="school"
if [ -e $file ]
then
       echo "$file file exists"

       if [ -s $file ]
       then
          echo "$file file is not empty"
       else
          echo "$file fie is empty"
       fi

       if [ -f $file ]
       then
          echo "$file is a regular file"
       fi
else
       echo "$file file does not exist"
fi
