#!/usr/bin/env bash
#checks the file and gives informations about the file
file="school"
if [ -e $file ]
then
       echo "$file file exists"

       if [ -s $file ]
       then
           echo "$file file is not empty"
       else
           echo "$file file is empty"
        fi

        if [ -f $file ] 
        then
        echo "$fie is a regular file"
        fi
else
      echo "$file file does not exist"
fi
