#!/bin/env bash
# this script displays a list of current running processes
# must show all processes, for all users, including those which might have a TTY
# displays in a user-oriented format
# show process hierachy

ps -a -x -u -f
